spring:
  application:
    name: your-car-your-way-chat-poc
  datasource:
    url: jdbc:h2:mem:chat;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  error:
    include-message: always
